name: Lint and Test

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
      - feat/*
      - fix/*
      - perf/*
      - "v[0-9]+"
      - "v[0-9]+.[0-9]+"

jobs:
  lint-and-test:
    name: Lint & Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Specify your project's Node version here
          cache: 'npm' # Optional but recommended: enables caching
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies (Verbose)
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Unit Tests
        run: npm test -- --run
